In [1]:
import os
import json
import seaborn as sns
import matplotlib .pyplot as plt
from sklearn .model_selection import train_test_split
import numpy as np

In [2]:
file_path = 'D:\\Dataset\\#4_전력 설비 에너지 패턴 및 고장 분석 센서\\Training\\1.펌프_일반모터\\2.SOH진단\\1.역률평균\\0.Combined\\'
files = ['Combined_LabelledData_346_역률평균.json', 'Combined_LabelledData_348_역률평균.json']
x_label = []
y_label = []

for file_name in files:
    full_path = file_path + file_name
    with open(full_path, 'r', encoding='utf-8') as file:
        data = json.load(file)

    for entry in data['data']:
        if entry['ITEM_NAME'] == "역률평균":
            x_label.append(entry['ITEM_VALUE'])
            if entry['LABEL_NAME']=='정상':
                y_label.append(0)
            elif entry['LABEL_NAME']=='경고':
                y_label.append(1) 
            else:
                y_label.append(2)

x_label = np.array(x_label)
x_label_scaled = (x_label - np.mean(x_label)) / np.std(x_label)



In [5]:
data_indices = np.arange(len(x_label))
print(data_indices)
np.random.shuffle(data_indices)
print(data_indices)

x_label = np.array(x_label)[data_indices]
y_label = np.array(y_label)[data_indices]

x_train, x_temp, y_train, y_temp = train_test_split(x_label, y_label, test_size=0.4, random_state=42)
x_valid, x_test, y_valid, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=42)
x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)

print(f"Train size: {len(x_train)}")
print(f"Validation size: {len(x_valid)}")
print(f"Test size: {len(x_test)}")

print(y_train)

print(y_train)

[    0     1     2 ... 57530 57531 57532]
[20329 52449 44069 ... 43289 40686 55607]
Train size: 34519
Validation size: 11507
Test size: 11507
[0 1 0 ... 0 1 2]
[0 1 0 ... 0 1 2]


In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import save_model, load_model

model_dnn = Sequential()
model_dnn.add(Dense(64, activation='relu', input_shape=(1,))) 
model_dnn.add(Dense(64, activation='relu'))
model_dnn.add(Dense(1)) 

model_dnn.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

x_train = x_train.reshape((x_train.shape[0], 1))

model_dnn.fit(x_train, y_train, epochs=10, batch_size=32)

model_dnn.save('dnn_model.h5')

Epoch 1/10
1079/1079 [==============================] - 1s 982us/step - loss: 0.4297 - accuracy: 0.4338
Epoch 2/10
1079/1079 [==============================] - 1s 995us/step - loss: 0.0181 - accuracy: 0.6266
Epoch 3/10
1079/1079 [==============================] - 1s 1ms/step - loss: 0.0100 - accuracy: 0.6267
Epoch 4/10
1079/1079 [==============================] - 1s 981us/step - loss: 0.0088 - accuracy: 0.6267
Epoch 5/10
1079/1079 [==============================] - 1s 995us/step - loss: 0.0075 - accuracy: 0.6267
Epoch 6/10
1079/1079 [==============================] - 1s 964us/step - loss: 0.0061 - accuracy: 0.6267
Epoch 7/10
1079/1079 [==============================] - 1s 970us/step - loss: 0.0050 - accuracy: 0.6267
Epoch 8/10
1079/1079 [==============================] - 1s 957us/step - loss: 0.0041 - accuracy: 0.6267
Epoch 9/10
1079/1079 [==============================] - 1s 995us/step - loss: 0.0035 - accuracy: 0.6267
Epoch 10/10
1079/1079 [==============================] - 1s 995us/